name: Build and Publish Single File

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: ubuntu-latest
            rid: linux-x64
            ext: ""
          - os: windows-latest
            rid: win-x64
            ext: ".exe"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet publish --self-contained -r ${{ matrix.rid }} -p:PublishSingleFile=true -c Release -o ./publish${{ matrix.ext }}

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: aws-inventory${{ matrix.ext }}
          path: ./publish${{ matrix.ext }}
