name: Build and Release

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      command:
        description: 'Build command'
        required: true
        default: 'build-windows'
        type: choice
        options:
          - build-windows
          - build-linux

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            rid: linux-x64
            ext: ""
            command: build-linux
          - os: windows-latest
            rid: win-x64
            ext: ".exe"
            command: build-windows

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.x

      - name: Restore dependencies
        if: ${{ matrix.command == github.event.inputs.command }}
        run: dotnet restore

      - name: Build project
        if: ${{ matrix.command == github.event.inputs.command }}
        run: dotnet publish --self-contained -r ${{ matrix.rid }} -p:PublishSingleFile=true -c Release -o ./publish${{ matrix.ext }}

      - name: Install GitHub CLI
        if: ${{ matrix.command == github.event.inputs.command }}
        run: sudo apt-get install -y gh

      - name: Authenticate GitHub CLI
        if: ${{ matrix.command == github.event.inputs.command }}
        run: echo ${{ secrets.GH_TOKEN }} | gh auth login --with-token

      - name: Create Release
        if: ${{ matrix.command == github.event.inputs.command }}
        run: |
          TAG_NAME=${{ matrix.command }}-$(date +'%Y%m%d%H%M%S')
          gh release create $TAG_NAME ./publish${{ matrix.ext }}/aws-inventory${{ matrix.ext }} -t "Release $TAG_NAME"
