name: Build and Release

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      command:
        description: 'Build command'
        required: true
        default: 'build-windows'
        type: choice
        options:
          - build-windows
          - build-linux

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            rid: linux-x64
            ext: ""
            command: build-linux
          - os: windows-latest
            rid: win-x64
            ext: ".exe"
            command: build-windows

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.x

      - name: Restore dependencies
        if: ${{ matrix.command == github.event.inputs.command }}
        run: dotnet restore

      - name: Build project
        if: ${{ matrix.command == github.event.inputs.command }}
        run: dotnet publish --self-contained -r ${{ matrix.rid }} -p:PublishSingleFile=true -c Release -o ./publish${{ matrix.ext }}

      - name: List root directory
        if: ${{ matrix.command == github.event.inputs.command }}
        run: ls -la ./

      - name: List publish directory
        if: ${{ matrix.command == github.event.inputs.command }}
        run: ls -la ./publish${{ matrix.ext }}

      - name: Install GitHub CLI (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y gh

      - name: Install GitHub CLI (Windows)
        if: matrix.os == 'windows-latest'
        run:
