name: Build and Release

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      command:
        description: 'Build command'
        required: true
        default: 'build-all'
        type: choice
        options:
          - build-all

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project for Linux
        run: dotnet publish --self-contained -r linux-x64 -p:PublishSingleFile=true -c Release -o ./publish/linux

      - name: Rename Linux binary
        run: mv ./publish/linux/AWS_Inventory ./publish/linux/AWS_Inventory_linux

      - name: Build project for Windows
        run: dotnet publish --self-contained -r win-x64 -p:PublishSingleFile=true -c Release -o ./publish/windows

      - name: Rename Windows binary
        run: mv ./publish/windows/AWS_Inventory.exe ./publish/windows/AWS_Inventory_win.exe

      - name: Build project for MacOS
        run: dotnet publish --self-contained -r osx-x64 -p:PublishSingleFile=true -c Release -o ./publish/macos

      - name: Rename MacOS binary
        run: mv ./publish/macos/AWS_Inventory ./publish/macos/AWS_Inventory_mac

      - name: List root directory
        run: ls -la ./

      - name: List publish directory
        run: ls -la ./publish

      - name: List Linux publish directory
        run: ls -la ./publish/linux

      - name: List Windows publish directory
        run: ls -la ./publish/windows

      - name: List MacOS publish directory
        run: ls -la ./publish/macos

      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh

      - name: Authenticate GitHub CLI
        run: echo ${{ secrets.GH_TOKEN }} | gh auth login --with-token

      - name: Delete existing release if exists
        run: |
          if gh release view latest_release; then
            gh release delete latest_release -y
          fi

      - name: Create Release
        run: |
          gh release create latest_release \
            ./publish/linux/AWS_Inventory_linux \
            ./publish/windows/AWS_Inventory_win.exe \
            ./publish/macos/AWS_Inventory_mac \
            -t "Release latest_release"
